application: module-skill-tree
version: 0-4
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
# Home page
- url: /
  script: home.app
  secure: always

# Skill Tree Management Pages
- url: /skilltree
  script: skill_tree.app
  secure: always

# Private Data
- url: /private_data/.*
  script: data.app
  login: required
  secure: always

# Public Data
- url: /data/.*
  script: data.app
  secure: always

# Image folder
- url: /images
  static_dir: images

# CSS folder
- url: /css
  static_dir: css

# Scripts folder
- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Under Construction
#- url: /.*
#  static_files: under_construction.html
#  upload: under_construction\.html

# Login page
- url: /login
  script: openid_login.app

# OpenID login page
- url: /_ah/login_required
  script: openid_login.app

# Administration pages
- url: /admin/.*
  script: admin.app
  login: admin

# Custom remote_api hanlder
#- url: /remote_api
#  script: remote_api.app

admin_console:
  pages:
  - name: Admin Home
    url: /admin/

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest