application: module-skill-tree
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Home page
- url: /
  script: home.app

# Skill Tree Management Pages
- url: /skilltree
  script: skill_tree.app
  secure: always

# Private Data
- url: /private_data/.*
  script: data.app
  login: required
  secure: always

# Public Data
- url: /data/.*
  script: data.app
  secure: always

# Image folder
- url: /images
  static_dir: images

# CSS folder
- url: /css
  static_dir: css

# Scripts folder
- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap
  
# OpenID login page
- url: /_ah/login_required
  script: openid_login.app

# Administration pages
- url: /admin/.*
  script: admin.app
  login: admin

# Any other unrecognized URL
- url: /.*
  static_files: not_found.html
  upload: not_found\.html

admin_console:
  pages:
  - name: Admin Home
    url: /admin/

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest
  